[package]
name = "tactica-api-types"
version = "0.1.0"
license.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

[features]
default = []
utoipa = ["dep:utoipa", "utoipa/chrono", "tactica-uuid-kinds/utoipa"]

[dependencies]
tactica-uuid-kinds = { workspace = true, features = ["serde"] }
chrono.workspace = true
serde.workspace = true
utoipa = { workspace = true, optional = true }

[lints]
workspace = true
