---
name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"
  RUST_BACKTRACE: "1"

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://git.hayden.moe/tactica/setup-repo-action@0bf4688b9e719c1f61e45e7dc06f378c522e41c5
      - run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://git.hayden.moe/tactica/setup-repo-action@0bf4688b9e719c1f61e45e7dc06f378c522e41c5
      - run: cargo build --workspace --all-features
      - run: cargo nextest run --workspace --all-features --no-fail-fast

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://git.hayden.moe/tactica/setup-repo-action@0bf4688b9e719c1f61e45e7dc06f378c522e41c5
      - run: cargo deny --all-features check

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://git.hayden.moe/tactica/setup-repo-action@0bf4688b9e719c1f61e45e7dc06f378c522e41c5
      - run: cargo doc --workspace --all-features --no-deps

  docker:
    runs-on: dind
    strategy:
      matrix:
        app: [tactica-api]
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://git.hayden.moe/tactica/setup-repo-action@0bf4688b9e719c1f61e45e7dc06f378c522e41c5
      - run: mise run build-docker "${{ matrix.app }}"
