---
name: Setup Repo
author: Tactica Team
description: |
  Configures Mise and sets up language caches.

inputs:
  bootstrap:
    description: Enable mise bootstrap
    default: 'false'

  cache:
    description: Enable caching
    default: 'true'

  rust:
    description: Enable Rust caching
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set system brew path
      if: inputs.bootstrap
      shell: bash
      run: echo "MISE_SYSTEM_BREW_PREFIX=/tmp/brew" >> "${GITHUB_ENV}"

    - name: Install Mise
      uses: jdx/mise-action@v4
      with:
        bootstrap: ${{ inputs.bootstrap }}
        cache: ${{ inputs.cache }}
        env: true
        experimental: true
        export_path: true

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache == 'true' && inputs.rust == 'true' }}
