[package]
name = "tactica-api"
version = "0.1.0"
license.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "tactica-api"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
axum = { workspace = true, features = ["multipart"] }
tower-http.workspace = true
utoipa.workspace = true
thiserror.workspace = true
anyhow.workspace = true
clap.workspace = true
url = "2"

tracing.workspace = true
tracing-subscriber.workspace = true

tactica-api-types = { workspace = true, features = ["utoipa"] }
tactica-auth.workspace = true
tactica-db-schema = { workspace = true, features = ["migrations"] }
tactica-db-model.workspace = true
tactica-db.workspace = true
tactica-uuid-kinds.workspace = true
tactica-permissions.workspace = true

tactica-files.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }

[dev-dependencies]
tempfile = "3"
serde_json = "1.0"
testcontainers-modules = { version = "0.15", features = ["postgres"] }
tower = { version = "0.5", features = ["util"] }

[lints]
workspace = true
