[settings]
experimental = true
auto_env = true

[settings.cargo]
binstall = true

[env]
_.file = ".env"
RUST_BACKTRACE = "1"

[tools]
"cargo:cargo-deny" = "0.20.2"
"cargo:cargo-machete" = "0.9.2"
"cargo:cargo-nextest" = "0.9.146"
"cargo:taplo-cli" = "0.10.0"
"cargo:typos-cli" = "1.50.2"
rust = "1.98.1"

[tasks.build]
description = "Build all of the released components of the workspace"
run = "cargo build --package tactica-api --release"

[tasks.fmt]
description = "Run rustfmt on the entire workspace"
run = ["cargo fmt --all", "taplo fmt"]

[tasks.check]
description = "Run all CI checks locally"
depends = ["lint", "test", "doc", "audit"]

[tasks.lint]
description = "Run fmt, clippy, typos, taplo, machete"
run = [
  "cargo fmt --all -- --check",
  "cargo clippy --workspace --all-targets --all-features -- -D warnings",
  "cargo machete",
  "taplo fmt --check",
  "typos",
]

[tasks.test]
description = "Run tests with nextest"
run = [
  "cargo nextest run --workspace --all-features --no-fail-fast",
  "cargo test --workspace --doc",
]

[tasks.audit]
description = "Run cargo-deny checks"
run = "cargo deny --all-features check"

[tasks.doc]
description = "Build docs with warnings as errors"
env = { RUSTDOCFLAGS = "-D warnings" }
run = "cargo doc --workspace --all-features --no-deps"

[tasks.migrate]
description = "Run database migrations"
env = { TACTICA_RUN_MIGRATIONS = "true" }
run = "cargo run --bin tactica-api"

[tasks.build-docker]
description = "Build docker image for the API"
usage = """
arg "<bin>" help="The binary to build"
"""
env.RUST_VERSION = { tools = true, value = "{{ tools.rust.version }}" }
run = """
docker build . \
  --build-arg BIN=${usage_bin} \
  --build-arg RUST_VERSION=${RUST_VERSION} \
  --file Dockerfile \
  --tag "${TACTICA_IMAGE_PREFIX:-git.hayden.moe/tactica/tactica}/api:${TACTICA_IMAGE_TAG:-dev}" \
"""

[tasks.gen-jwt-keys]
description = "Generate JWT keys for the API"
run = """
rm -rf "{{ config_root }}/.local/jwt.key" "{{ config_root }}/.local/jwt.pem"
openssl genpkey -algorithm ed25519 -out "{{ config_root }}/.local/jwt.key"
openssl pkey -in "{{ config_root }}/.local/jwt.key" -pubout -out "{{ config_root }}/.local/jwt.pem"
"""
