[package]
name = "tactica-db"
version = "0.1.0"
license.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
diesel.workspace = true
diesel-async.workspace = true
chrono.workspace = true

tactica-uuid-kinds.workspace = true
tactica-db-schema.workspace = true
tactica-db-model.workspace = true
tactica-permissions.workspace = true

[dev-dependencies]
tokio.workspace = true
testcontainers-modules = { version = "0.15", features = ["postgres"] }
tactica-db-schema = { workspace = true, features = ["migrations"] }

[lints]
workspace = true
