[package]
name = "tactica-db"
version = "0.1.0"
license.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

[features]
integration = []

[dependencies]
async-trait.workspace = true
diesel.workspace = true
diesel-async.workspace = true
chrono.workspace = true

tactica-uuid-kinds.workspace = true
tactica-db-schema.workspace = true
tactica-db-model.workspace = true
tactica-permissions.workspace = true

[dev-dependencies]
tokio.workspace = true
testcontainers-modules = { version = "0.15", features = ["postgres"] }
tactica-db-schema = { workspace = true, features = ["migrations"] }

[[test]]
name = "integration_refresh_sessions"
path = "tests/refresh_sessions.rs"
required-features = ["integration"]

[[test]]
name = "integration_unit_create"
path = "tests/unit_create.rs"
required-features = ["integration"]

[[test]]
name = "integration_unit_member_roles"
path = "tests/unit_member_roles.rs"
required-features = ["integration"]

[lints]
workspace = true
