[package]
name = "tactica-api"
version = "0.1.0"
license.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "tactica-api"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
axum.workspace = true
tower-http.workspace = true
utoipa.workspace = true
thiserror.workspace = true
anyhow.workspace = true
clap.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

tactica-api-types = { workspace = true, features = ["utoipa"] }
tactica-auth.workspace = true
tactica-db-schema = { workspace = true, features = ["migrations"] }
tactica-db-model.workspace = true
tactica-db.workspace = true

[lints]
workspace = true
