---
name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect web changes
    runs-on: ubuntu-26.04
    outputs:
      web: ${{ steps.web.outputs.any_modified }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check changed web files
        id: web
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: web/**
          include_all_old_new_renamed_files: true

  rust:
    name: Rust
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/rust.yaml

  web:
    if: needs.changes.outputs.web
    name: Web
    needs: changes
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/web.yaml
